# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: buffer.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
'''
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'buffer.proto'
)'''
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x62uffer.proto\x12\x05rover\"\x1d\n\nmapRequest\x12\x0f\n\x07request\x18\x01 \x01(\t\"5\n\x08mapReply\x12\x0b\n\x03map\x18\x01 \x01(\t\x12\x0c\n\x04rows\x18\x02 \x01(\t\x12\x0e\n\x06\x63olumn\x18\x03 \x01(\t\"\"\n\x0e\x63ommandRequest\x12\x10\n\x08roverNum\x18\x01 \x01(\t\"\x1d\n\x0c\x63ommandReply\x12\r\n\x05moves\x18\x01 \x01(\t\"+\n\x17mineSerialNumberRequest\x12\x10\n\x08roverPos\x18\x01 \x01(\t\"*\n\x15mineSerialNumberReply\x12\x11\n\tserialNum\x18\x01 \x01(\t\" \n\x0esuccessRequest\x12\x0e\n\x06status\x18\x01 \x01(\t\" \n\x0csuccessReply\x12\x10\n\x08response\x18\x01 \x01(\t\"!\n\x0eminePinRequest\x12\x0f\n\x07mineNum\x18\x01 \x01(\t\"\x1b\n\x0cminePinReply\x12\x0b\n\x03pin\x18\x01 \x01(\t2\xcb\x02\n\rGroundControl\x12.\n\x06getMap\x12\x11.rover.mapRequest\x1a\x0f.rover.mapReply\"\x00\x12;\n\x0bgetCommands\x12\x15.rover.commandRequest\x1a\x13.rover.commandReply\"\x00\x12U\n\x13getMineSerialNumber\x12\x1e.rover.mineSerialNumberRequest\x1a\x1c.rover.mineSerialNumberReply\"\x00\x12:\n\ngetSuccess\x12\x15.rover.successRequest\x1a\x13.rover.successReply\"\x00\x12:\n\ngetMinePin\x12\x15.rover.minePinRequest\x1a\x13.rover.minePinReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'buffer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MAPREQUEST']._serialized_start=23
  _globals['_MAPREQUEST']._serialized_end=52
  _globals['_MAPREPLY']._serialized_start=54
  _globals['_MAPREPLY']._serialized_end=107
  _globals['_COMMANDREQUEST']._serialized_start=109
  _globals['_COMMANDREQUEST']._serialized_end=143
  _globals['_COMMANDREPLY']._serialized_start=145
  _globals['_COMMANDREPLY']._serialized_end=174
  _globals['_MINESERIALNUMBERREQUEST']._serialized_start=176
  _globals['_MINESERIALNUMBERREQUEST']._serialized_end=219
  _globals['_MINESERIALNUMBERREPLY']._serialized_start=221
  _globals['_MINESERIALNUMBERREPLY']._serialized_end=263
  _globals['_SUCCESSREQUEST']._serialized_start=265
  _globals['_SUCCESSREQUEST']._serialized_end=297
  _globals['_SUCCESSREPLY']._serialized_start=299
  _globals['_SUCCESSREPLY']._serialized_end=331
  _globals['_MINEPINREQUEST']._serialized_start=333
  _globals['_MINEPINREQUEST']._serialized_end=366
  _globals['_MINEPINREPLY']._serialized_start=368
  _globals['_MINEPINREPLY']._serialized_end=395
  _globals['_GROUNDCONTROL']._serialized_start=398
  _globals['_GROUNDCONTROL']._serialized_end=729
# @@protoc_insertion_point(module_scope)
