# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import buffer_pb2 as buffer__pb2

GRPC_GENERATED_VERSION = '1.68.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in buffer_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GroundControlStub(object):
    """Ground Control service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getMap = channel.unary_unary(
                '/rover.GroundControl/getMap',
                request_serializer=buffer__pb2.mapRequest.SerializeToString,
                response_deserializer=buffer__pb2.mapReply.FromString,
                _registered_method=True)
        self.getCommands = channel.unary_unary(
                '/rover.GroundControl/getCommands',
                request_serializer=buffer__pb2.commandRequest.SerializeToString,
                response_deserializer=buffer__pb2.commandReply.FromString,
                _registered_method=True)
        self.getMineSerialNumber = channel.unary_unary(
                '/rover.GroundControl/getMineSerialNumber',
                request_serializer=buffer__pb2.mineSerialNumberRequest.SerializeToString,
                response_deserializer=buffer__pb2.mineSerialNumberReply.FromString,
                _registered_method=True)
        self.getSuccess = channel.unary_unary(
                '/rover.GroundControl/getSuccess',
                request_serializer=buffer__pb2.successRequest.SerializeToString,
                response_deserializer=buffer__pb2.successReply.FromString,
                _registered_method=True)
        self.getMinePin = channel.unary_unary(
                '/rover.GroundControl/getMinePin',
                request_serializer=buffer__pb2.minePinRequest.SerializeToString,
                response_deserializer=buffer__pb2.minePinReply.FromString,
                _registered_method=True)


class GroundControlServicer(object):
    """Ground Control service definition
    """

    def getMap(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getCommands(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getMineSerialNumber(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getSuccess(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getMinePin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GroundControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getMap': grpc.unary_unary_rpc_method_handler(
                    servicer.getMap,
                    request_deserializer=buffer__pb2.mapRequest.FromString,
                    response_serializer=buffer__pb2.mapReply.SerializeToString,
            ),
            'getCommands': grpc.unary_unary_rpc_method_handler(
                    servicer.getCommands,
                    request_deserializer=buffer__pb2.commandRequest.FromString,
                    response_serializer=buffer__pb2.commandReply.SerializeToString,
            ),
            'getMineSerialNumber': grpc.unary_unary_rpc_method_handler(
                    servicer.getMineSerialNumber,
                    request_deserializer=buffer__pb2.mineSerialNumberRequest.FromString,
                    response_serializer=buffer__pb2.mineSerialNumberReply.SerializeToString,
            ),
            'getSuccess': grpc.unary_unary_rpc_method_handler(
                    servicer.getSuccess,
                    request_deserializer=buffer__pb2.successRequest.FromString,
                    response_serializer=buffer__pb2.successReply.SerializeToString,
            ),
            'getMinePin': grpc.unary_unary_rpc_method_handler(
                    servicer.getMinePin,
                    request_deserializer=buffer__pb2.minePinRequest.FromString,
                    response_serializer=buffer__pb2.minePinReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rover.GroundControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rover.GroundControl', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GroundControl(object):
    """Ground Control service definition
    """

    @staticmethod
    def getMap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rover.GroundControl/getMap',
            buffer__pb2.mapRequest.SerializeToString,
            buffer__pb2.mapReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getCommands(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rover.GroundControl/getCommands',
            buffer__pb2.commandRequest.SerializeToString,
            buffer__pb2.commandReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getMineSerialNumber(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rover.GroundControl/getMineSerialNumber',
            buffer__pb2.mineSerialNumberRequest.SerializeToString,
            buffer__pb2.mineSerialNumberReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getSuccess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rover.GroundControl/getSuccess',
            buffer__pb2.successRequest.SerializeToString,
            buffer__pb2.successReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getMinePin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rover.GroundControl/getMinePin',
            buffer__pb2.minePinRequest.SerializeToString,
            buffer__pb2.minePinReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
